dist: xenial

sudo: required

services:
  - docker

language: python

python:
  - "3.7"

before_install:
  - mkdir -p ~/Documents/sftp/ppo_dev
  - mkdir -p ~/Documents/sftp/qmprint_dev

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - make build_and_test

after_success:
  - pipenv run codecov

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - master
