dist: xenial

sudo: required

services:
  - docker

language: python

python:
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev --deploy

script:
  - pwd
  - ls -la
  - mkdir working_files
  - mkdir working_files/partial_files && mkdir working_files/encrypted_files && mkdir working_files/quarantined_files
  - sudo chmod -R 777 working_files/
  - make build_and_integration_tests_no_clean

after_success:
  - pipenv run codecov

after_failure:
  - docker logs dev-print-file-service
env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

branches:
  only:
    - master
